#!/usr/bin/env bash
#
# Install dotfiles.
#

usage() {
    cat <<EOF
Usage: ${0##*/}

  Options:
    -h              display this help message
EOF
}

while getopts "h" opt; do
    case $opt in
        h) # display usage message
            usage
            exit 0
            ;;
    esac
done

cd "$(dirname "$0")"

cp -vR $(find home -mindepth 1 -maxdepth 1) "$HOME"

echo "appending hibernate/suspend aliases to ~/.zshrc..."
echo "
# Aliases for Samsung NP-Q1U tablet

## easy hibernation
alias h='systemctl hibernate'

## easy suspend
alias s='systemctl suspend'

## easy mount 
alias m='mount'

## easy video playback
alias p='mplayer -fs'

## easy ncmpcpp
alias nc='ncmpcpp'" >> ~/.zshrc
